name: 'Example TypeScript Action'
description: 'A simple TypeScript GitHub Action'
branding:
  icon: code
  color: blue
author: 'flcdrg'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
