# This is a basic workflow to help you get started with Actions

name: test-action

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Example TypeScript Action

      uses: flcdrg/example-ts-action@v1.2
      id: thing
      with:
        # input description here
        milliseconds: 1000

    - name: Result
      run: echo "${{ steps.thing.outputs.time }}"